name: gestao_de_treinos_flutter_front
description: "Aplicativo para transferência de itens entre endereços de estoque."
publish_to: 'none'
version: 1.0.0+1

scripts:
  build: "dart run build_runner build"
  webCors: 'flutter run -d chrome --web-browser-flag "--disable-web-security"'

environment:
  sdk: '>=3.4.1 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/images/treinos.jpg
    - assets/images/homem.png

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  kongelado_annotation:
    path: ../App/flutter_packages_kugel/kongelado_annotation
  intl: ^0.19.0
  get: ^4.6.6
  get_storage: ^2.1.1
  path_provider: ^2.1.3
  flutter_hooks: ^0.20.5
  go_router: ^14.3.0
  hooks_riverpod: ^2.5.2
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  freezed: ^2.4.7
  google_fonts: ^6.2.1
  fluentui_system_icons: ^1.1.259
  riverpod_annotation: ^2.3.5
  retrofit: ^4.4.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  toastification: ^2.3.0
  progress_indicator: ^0.2.2
  barcode_scanner: ^6.1.1
  simple_barcode_scanner: ^0.3.0
  flutter_datawedge: ^3.1.0
  internet_connection_checker: ^3.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.11
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  kongelado_generator:
    path: ../App/flutter_packages_kugel/kongelado_generator
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  image_path: "assets/images/homem.png"
  android: true
  ios: true
  remove_alpha_ios: true